### ISSUE TITLE
Should `pandas` be an optional dependency?

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#261]
This is very similar to the discussion in #233 about making `pins` DF-library agnostic.

I'm in two minds about this.

On the one hand, the vast majority of the time, anyone who wants to use `pins` will be using `pandas`.
On the other hand, that means they would already have it installed, making it unlikely that `pandas` being optional would cause major friction.

Making it optional would enable `polars` users etc. to use `pins` without needing to install `pandas` (see #153).

It is being considered to add `pyarrow` as a required dependency to pandas which would increase the installation size by ~120MB.
https://github.com/pandas-dev/pandas/issues/54466

The costs to this project would be additional code complexity to protect import statements with `try-except`, as well as potentially some internal refactoring (e.g. `as_df` options).

**Comment by isabelizimm** [comment]
For pins in the short/medium-term future, I would be more keen to have `pandas` built-in and expand the ability to use polars/any other dataframe library as desired. I do believe `pins` should have at least one reasonable data frame library "batteries included" to have the ability to read data, perhaps pinned by a colleague or from R, as a data frame without having to make a decision on what library that is/seeing errors if there is no dataframe library installed. 

I could see a world where the default library is polars instead of pandas, but I do think pandas still has the masses for now.

**Comment by nathanjmcdougall** [comment]
Sounds good to me.
