### ISSUE TITLE
Add `rdata` as a test dependency

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#262]
At the moment, `rdata` is similar to `pyarrow`, etc. in the sense that it is optional, but still needed for testing and so I think it should be explicitly declared as a optional test dependency in `setup.cfg`.

This will mean it can be added as a pinned version to `requirements/dev.txt` rather than installed separately. This ensures consistency between local dev and CI and also ensures there is a consistent dependency resolution with dev.txt together with the `rdata` package.

I would like to do this, then the separate install step could be removed:
https://github.com/rstudio/pins-python/blob/70380b4532f3778e4777888507a49c2d1cab1ae8/.github/workflows/ci.yml#L90-L95

Incidentally, I am not sure why `python -m pip install -e .[test]` is necessary since the `test` extra is already included in the `dev.txt` file. I think this could be removed too.

**Comment by nathanjmcdougall** [comment]
This is also the only thing keeping us from using `reportMissingImports = true` in Pyright (see #256).

**Comment by isabelizimm** [comment]
Thanks for this bit of cleanup, this all seems great! I want to make sure that there is at least one set of tests run that does not include all the test dependencies, but that should be covered by the [min test requirements CI run](https://github.com/rstudio/pins-python/blob/641e5114f274091dc5c24327f345b79d9b052d04/.github/workflows/ci.yml#L30). You are correct; it should be `python -m pip install -e .` 👀 `pyarrow` and `fastparquet` were not part of `dev.txt` when that line was added, but we have since updated that requirements file to be comprehensive.
