### ISSUE TITLE
Bugfix: missing information in version parsing error message

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#281]
The string doesn't actually use `dt_string`:

https://github.com/rstudio/pins-python/blob/d215a8cd6cf958be0f4fc41c6e90e21c907b4655/pins/versions.py#L82

When fixing this, I propose I enable the pyupgrade `UP` rules from ruff. This would move all strings to use `.format` instead of `% ...` via [`UP031`](https://docs.astral.sh/ruff/rules/printf-string-formatting/), and then this bug would subsequently be caught via [`F523`](https://docs.astral.sh/ruff/rules/string-dot-format-extra-positional-arguments/).

Apart from `UP031`, the code already complies with all `UP` rules.

**Comment by isabelizimm** [comment]
Ah, I don't think I would want to turn on all the `UP` rules from ruff unless it is minimal friction, but at the very least `UP031` seems like a good plan! When these different rules get added, it would also be nice to have a little explanation of what it does (since I will certainly forget all these codes 😆)

**Comment by nathanjmcdougall** [comment]
> unless it is minimal friction
As I say, the code already complies with all the rules except `UP031` so I figure it doesn't hurt to enable them all 🤷 
Happy either way.
